### ISSUE TITLE
Using miniKanren-with-symbolic-constraints and Petite Chez Scheme

### ISSUE THREAD

**Issue by Andrew-Zipperer** [webyrd/miniKanren-with-symbolic-constraints#1]
Hello!

Thank you for these files. 

Issue:
I am encountering (a) a slight infelicity and (b) an unexpected error and while using these files and Petite Chez Scheme (PCS). 

Description of errors with light background: 
I am presently reading 'The Reasoned Schemer'. My intention is to use these files and an interactive shell of PCS to type the  examples from the book and experiment. I have saved the mini-Kanren-with-symbolic-constraints files in a directory. In a terminal window, I navigate to this directory and open an instance of PCS; then -- in accordance with the markdown file -- I (load "mk.scm") and (load "test-all.scm").  All the tests pass. 

  (a) the slight infelicity:
  When I type "succeed" (i.e. > succeed), the output is #<procedure>. 
  When I type "fail" (i.e. > fail), the output is #<procedure>. 
  When a user inputs a goal, the output is #<procedure>.
  So, since the output is the same for both "succeed" and "fail" when a user inputs a goal, the user cannot decide using the output whether the goal succeeds or fails. 

  In order to test whether a goal succeeds or fails, I have been inserting the goal into a cond expression (e.g. (cond [<goal> 'a] [else 'b])). then checking whether the output is a or b. 

  Is this the standard way of checking whether a goal succeeds or fails? 

  (b) the unexpected error:
  In the book, the first question I encountered that uses conde is question 44. My translation (from the book's typesetting to Scheme) of the expression in that question is:
    (conde 
      (fail succeed)
      (else fail))
  When I enter this into a PCS shell, I get an error message "Exception: misplaced aux keyword (else c) near line 210, char 23 of mk.scm"

  When I enter:
    (conde 
      (fail succeed)
      (fail))
  I get #<procedure>, as expected.

  Is this second rendering (without `else') the appropriate translation? i.e. should I ignore`else''s in the book when translating from the book to the shell? 

Thanks again!

Best wishes, 
Andrew

P.S. I am a noob. Sorry if these are questions I should be resolving on my own.

**Comment by Andrew-Zipperer** [comment]
When I wrote the above, I used left-carets and right-carets. e.g. I wrote #left-caret procedure right-caret. 
As it is rendered above, the left-caret procedure right-caret after # is dropped.

**Comment by Andrew-Zipperer** [comment]
ugh -- this same dropping-the-carets issue mangled part (a) too; I used carets there as well. There, when I said I was putting the goal in a cond expression, the intended cond expression was (cond [ _goal 'a] [else 'b]). 

I have since realized that I was more confused than I recognized. 
I expected (cond [fail 'a] [else 'b]) to have value 'b.

**Comment by webyrd** [comment]
Hi Andrew!

Thanks for the questions, and for the interest in miniKanren!

There are actually many implementations of miniKanren at this point.  (For example, see the list of implementations at http://minikanren.org/).  The implementation in this repository is somewhat different than the one in 'The Reasoned Schemer', and both simplifies and extends the language of the book.

Since 'The Reasoned Schemer' came out we have simplified the language somewhat.  We removed 'else' from 'conde', removed 'condi' and 'alli' (and rolled their behavior into an improved 'conde'), and made a few other changes.  These changes are reflected in this repository, which is why you had to remove the 'else'. 

The latest, and fastest, implementation of extended miniKanren is actually this one:

https://github.com/michaelballantyne/faster-miniKanren

Once again, this newer implementation gets rid of 'alli' and 'condi', and gets rid of the 'else' in 'conde'.

If you are working through 'The Reasoned Schemer', I suggest using this code instead, which matches the implementation and examples of the book:

https://github.com/miniKanren/TheReasonedSchemer

(Once you understand the book, though, the newer 'conde' is quite nice!)

```
>  I am encountering (a) a slight infelicity and (b) an unexpected error and while using these files and Petite Chez Scheme (PCS). 
```

Happily, the full implementation of Chez Scheme is now open source!

https://github.com/cisco/ChezScheme

Full Chez is faster than Petite.  It shouldn't matter for the examples in the book, but for larger miniKanren programs the extra speed of full Chez helps.

> Is this second rendering (without else') the appropriate translation? i.e. should I ignoreelse''s in the book when translating from the book to the shell? 

Yes, if you are using the implementation in this repo, or in https://github.com/michaelballantyne/faster-miniKanren.  I recommend using https://github.com/miniKanren/TheReasonedSchemer, which still uses the 'else' in 'conde', and which is generally faithful to the book.

```
 > When I type "succeed" (i.e. > succeed), the output is #. 
```

I assume you mean to type `#<procedure>`:

```
> succeed
#<procedure>
> fail
#<procedure>
```

'succeed' and 'fail' are _goals_, which, as you will find out later in the book, are procedures that take a _substitution_ and return a _stream of substitutions_.  These are implementation-level details that you shouldn't concern yourself with at this point.

The point is that, in order to see their behavior, you must use 'succeed' and 'fail' within a 'run' or 'run*' expression.  For example:

```
> (run* (q) succeed)
(_.0)
```

versus

```
> (run* (q) fail)
()
```

Does this help clarify things?

Cheers,

--Will

**Comment by Andrew-Zipperer** [comment]
Hi, Will

This does clarify things -- thank you very much!
Thank you for the reference to the different implementations, the notes about their differences, and the explanation of my issues using those differences. And the heads up about full Chez Scheme being open source now. 

I am now using the recommended implementation hosted here: https://github.com/miniKanren/TheReasonedSchemer. 
Everything is working as expected so far!
And the method I am using to check the success/failure of a given goal (say, g) is:
  (run #f (q) g (== q #t))
where a value of () indicates that g fails and a value of (#t) indicates that g succeeds. 

Thank you again!
Andrew
